version: '3.4'

services:
  es_document:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TZ=Asia/Ho_Chi_Minh
    ports:
      - "7000:3000"
    restart: always
    networks:
      - esplfdoc-network
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "1"

networks:
  esplfdoc-network:
    external:
      name: esplf-network