version: '3.4'

services:
  espfdocument:
    build:
      context: src
    environment:
      - TZ=Asia/Ho_Chi_Minh
    ports:
      - "7000:3000"
    restart: always
    networks:
      - espfdoc-network
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "1"

networks:
  espfdoc-network:
    external:
      name: espf-network 
    
